#pragma once

extern "C" int dnaupd_(int *ido,
                       char *bmat,
                       int *n,
                       char *which,
                       int *nev,
                       double *tol,
                       double *resid,
                       int *ncv,
                       double *v,
                       int *ldv,
                       int *iparam,
                       int *ipntr,
                       double *workd,
                       double *workl,
                       int *lworkl,
                       int *info);

extern "C" int dneupd_(int *rvec,
                       char *howmny,
                       int *select,
                       double *dr,
                       double *di,
                       double *z,
                       int *ldz,
                       double *sigmar,
                       double *sigmai,
                       double *workev,
                       char *bmat,
                       int *n,
                       char *which,
                       int *nev,
                       double *tol,
                       double *resid,
                       int *ncv,
                       double *v,
                       int *ldv,
                       int *iparam,
                       int *ipntr,
                       double *workd,
                       double *workl,
                       int *lworkl,
                       int *info);
